var types = {
    UPDATE_TICKER: 'UPDATE_TICKER',
    SOCKET_OPEN: 'SOCKET_OPEN',
    SOCKET_CLOSE: 'SOCKET_CLOSE',
    SOCKET_ERROR: 'SOCKET_ERROR',
    SOCKET_MESSAGE: 'SOCKET_MESSAGE',
    SOCKET_CONNECT: 'SOCKET_CONNECT',
    SOCKET_SEND: 'SOCKET_SEND',
    SOCKET_SUBSCRIBED: 'SOCKET_SUBSCRIBED'
}

export default types;